### ISSUE TITLE
Online Demo is broken

### ISSUE THREAD

**Issue by fishermans** [miguelperezcolom/mateu-mdd#7]
Hi,

It seems that the online demo is down:  http://mdddemo.mateu.io/

Thanks

**Comment by miguelperezcolom** [comment]
Thank you very much, fishermans.

Changed the link to https://demo.quotravel.eu/, which shows a real enterprise app made with Mateu MDD. I think there is no better demo than this ;)

Best,

Miguel

**Comment by miguelperezcolom** [comment]
solved
